# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, asn1Types, attoparsec, blazeBuilder, blazeHtml
, conduit, dataDefault, esqueleto, fastLogger, fileEmbed
, highlighter, hjsmin, hspec, httpConduit, httpTypes, lens
, liftedBase, markdown, monadControl, monadLogger, MonadRandom
, network, pathPieces, pcreLight, persistent, persistentPostgresql
, persistentTemplate, resourcet, shakespeare, text, thyme
, transformers, wai, waiExtra, waiLogger, warp, yaml, yesod
, yesodAuth, yesodCore, yesodForm, yesodNewsfeed, yesodPagination
, yesodStatic, yesodTest, stdenv

, postgresql

, preBuild ? ""
}:

cabal.mkDerivation (self: {
  pname = "webapp2";
  version = "0.0.0";
  src = stdenv.lib.sourceFilesBySuffices ./. [
    ".cabal" ".hs" ".lucius" ".msg" "models" "routes"
    # ".cabal" ".coffee" ".eot" ".hamlet" ".hs" ".ico" ".julius" ".lucius" ".msg" ".png"
    # ".svg" ".text" ".ttf" ".txt" ".woff" ".yml" "models" "routes"
  ];
  doCheck = false;
  noHaddock = true;
  isLibrary = true;
  isExecutable = true;
  buildTools = [ postgresql ];
  buildDepends = [
    aeson asn1Types attoparsec blazeBuilder blazeHtml conduit
    dataDefault esqueleto fastLogger fileEmbed highlighter hjsmin
    httpConduit httpTypes lens markdown monadControl monadLogger
    MonadRandom network pathPieces pcreLight persistent
    persistentPostgresql persistentTemplate shakespeare text thyme wai
    waiExtra waiLogger warp yaml yesod yesodAuth yesodCore yesodForm
    yesodNewsfeed yesodPagination yesodStatic
  ];
  testDepends = [
    hspec liftedBase monadLogger persistent persistentPostgresql
    resourcet text transformers yesod yesodCore yesodTest
  ];
  inherit preBuild;
  postInstall = ''
    cp -pR static $out/static
    cp -pR config $out/config
  '';
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
