#!/bin/bash

echo -n "Updating code..."
cd /opt/git/otte.rs.git
GIT_WORK_TREE=/srv/http/otte.rs git checkout -f HEAD >/dev/null || exit 1
echo "all done."

cd /srv/http/otte.rs

echo -n "Updating gems..."
SSL_CERT_FILE=/usr/local/etc/ssl/cacert.pem bundle install --deployment >/dev/null || exit 1
echo -n "compiling assets..."
bundle exec rake update_token || exit 1
RAILS_ENV=production bundle exec rake assets:precompile db:migrate 2>/dev/null || exit 1
echo -n "starting webserver..."
bundle exec thin start --port 39410 --env production --daemonize --pid /run/otters/otte.rs.pid >/dev/null
echo "done."
